-- пользователи новой системы
CREATE TABLE IF NOT EXISTS company_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login VARCHAR(255) NOT NULL,
  CONSTRAINT company_user_uniq_login UNIQUE (login)
);

-- пациенты новой системы
CREATE TABLE IF NOT EXISTS patient_profile (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(255),
  last_name  VARCHAR(255),
  old_client_guid VARCHAR(255), -- список guid через запятую
  status_id SMALLINT NOT NULL
);

-- заметки
CREATE TABLE IF NOT EXISTS patient_note (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_date_time      TIMESTAMP NOT NULL,
  last_modified_date_time TIMESTAMP NOT NULL,
  created_by_user_id     BIGINT,
  last_modified_by_user_id BIGINT,
  note VARCHAR(4000),
  patient_id BIGINT NOT NULL,
  CONSTRAINT fk_pat_note_to_modified_user FOREIGN KEY (last_modified_by_user_id) REFERENCES company_user(id),
  CONSTRAINT fk_pat_note_to_created_user  FOREIGN KEY (created_by_user_id)       REFERENCES company_user(id),
  CONSTRAINT fk_pat_note_to_patient       FOREIGN KEY (patient_id)               REFERENCES patient_profile(id)
);