spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/legacy_import
    username: legacy_user
    password: legacy_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Europe/Warsaw

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.example.test_clever.support.LegacyClientSmoke: ERROR
    com.example.test_clever.legacy: INFO
    com.example.test_clever.scheduler: INFO

legacy:
  api:
    base-url: http://localhost:9090
    connect-timeout-ms: 3000
    read-timeout-ms: 5000
